language: python
python:
  - "3.6"
install:
  - pip install -r requirements.dev.txt
  - pip install coverage python-coveralls
script:
  - coverage run -m nose server spider validator
after_success:
  - coveralls
