language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script:
  - nosetests server/ spider/ validator --with-coverage
after_success:
  - coveralls
