version: "3.4"

services:
  server:
    build: ./server_deploy
    depends_on:
      - mongo
    ports:
      - "3080:3080"
    volumes:
      - ".:/app/server"
  validator:
    build: ./validator_deploy
    depends_on:
      - mongo
    volumes:
      - ".:/app/validator"
  spider:
    build: ./spider_deploy
    depends_on:
      - mongo
    volumes:
      - ".:/app/spider"
  mongo:
    image: mongo:3.5
    ports:
      - "37017:27017"
    volumes:
      - "mongo:/data/db"

volumes:
  mongo: 
  