from proxy_crawler.spiders.cnproxy import CNProxySpider
from proxy_crawler.spiders.goubanjia import GouBanJiaSpider
from proxy_crawler.spiders.ip181 import Ip181Spider
from proxy_crawler.spiders.kuaidaili import KuaiDaiLiSpider
from proxy_crawler.spiders.kxdaili import KXDaiLiSpider
from proxy_crawler.spiders.premproxy import PremProxySpider
from proxy_crawler.spiders.proxydb import ProxyDBSpider
from proxy_crawler.spiders.xici import XiCiSpider
from proxy_crawler.models import bind_models
